FROM  ubuntu

#CMD ["echo", "Hello World"]
RUN apt-get update

RUN apt-get install tzdata
ENV TZ=Europe/Stockholm
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN apt-get install apache2 -y
RUN apt-get install apache2-utils -y
RUN apt-get clean


COPY index.html /var/www/html/
CMD ["usr/sbin/httpd", "-D", "FOREGROUND"]
EXPOSE 80
